version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    ports:
      - "3001:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    depends_on:
      - ml_api

  ml_api:
    build:
      context: ./backend/ml_model
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
